// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.xiang.proto.gym.nano;

@SuppressWarnings("hiding")
public interface Gym {

  public static final class Request13001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional float longitude = 1;
      public float longitude;

      // optional float latitude = 2;
      public float latitude;

      // optional int32 pageIndex = 3;
      public int pageIndex;

      public Params() {
        clear();
      }

      public Params clear() {
        longitude = 0F;
        latitude = 0F;
        pageIndex = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (java.lang.Float.floatToIntBits(this.longitude)
            != java.lang.Float.floatToIntBits(0F)) {
          output.writeFloat(1, this.longitude);
        }
        if (java.lang.Float.floatToIntBits(this.latitude)
            != java.lang.Float.floatToIntBits(0F)) {
          output.writeFloat(2, this.latitude);
        }
        if (this.pageIndex != 0) {
          output.writeInt32(3, this.pageIndex);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (java.lang.Float.floatToIntBits(this.longitude)
            != java.lang.Float.floatToIntBits(0F)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeFloatSize(1, this.longitude);
        }
        if (java.lang.Float.floatToIntBits(this.latitude)
            != java.lang.Float.floatToIntBits(0F)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeFloatSize(2, this.latitude);
        }
        if (this.pageIndex != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(3, this.pageIndex);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 13: {
              this.longitude = input.readFloat();
              break;
            }
            case 21: {
              this.latitude = input.readFloat();
              break;
            }
            case 24: {
              this.pageIndex = input.readInt32();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request13001[] _emptyArray;
    public static Request13001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request13001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.gym.Request13001.Params params = 2;
    public com.xiang.proto.gym.nano.Gym.Request13001.Params params;

    public Request13001() {
      clear();
    }

    public Request13001 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request13001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.gym.nano.Gym.Request13001.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request13001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request13001(), data);
    }

    public static Request13001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request13001().mergeFrom(input);
    }
  }

  public static final class Response13001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .com.xiang.proto.BriefGym briefGyms = 1;
      public com.xiang.proto.nano.Common.BriefGym[] briefGyms;

      // optional int32 maxCountPerPage = 2;
      public int maxCountPerPage;

      public Data() {
        clear();
      }

      public Data clear() {
        briefGyms = com.xiang.proto.nano.Common.BriefGym.emptyArray();
        maxCountPerPage = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.briefGyms != null && this.briefGyms.length > 0) {
          for (int i = 0; i < this.briefGyms.length; i++) {
            com.xiang.proto.nano.Common.BriefGym element = this.briefGyms[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        if (this.maxCountPerPage != 0) {
          output.writeInt32(2, this.maxCountPerPage);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.briefGyms != null && this.briefGyms.length > 0) {
          for (int i = 0; i < this.briefGyms.length; i++) {
            com.xiang.proto.nano.Common.BriefGym element = this.briefGyms[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        if (this.maxCountPerPage != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.maxCountPerPage);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.briefGyms == null ? 0 : this.briefGyms.length;
              com.xiang.proto.nano.Common.BriefGym[] newArray =
                  new com.xiang.proto.nano.Common.BriefGym[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.briefGyms, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new com.xiang.proto.nano.Common.BriefGym();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new com.xiang.proto.nano.Common.BriefGym();
              input.readMessage(newArray[i]);
              this.briefGyms = newArray;
              break;
            }
            case 16: {
              this.maxCountPerPage = input.readInt32();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response13001[] _emptyArray;
    public static Response13001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response13001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.gym.Response13001.Data data = 2;
    public com.xiang.proto.gym.nano.Gym.Response13001.Data data;

    public Response13001() {
      clear();
    }

    public Response13001 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response13001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.gym.nano.Gym.Response13001.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response13001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response13001(), data);
    }

    public static Response13001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response13001().mergeFrom(input);
    }
  }

  public static final class Request13002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional int32 gymId = 1;
      public int gymId;

      public Params() {
        clear();
      }

      public Params clear() {
        gymId = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.gymId != 0) {
          output.writeInt32(1, this.gymId);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.gymId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, this.gymId);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.gymId = input.readInt32();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request13002[] _emptyArray;
    public static Request13002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request13002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.gym.Request13002.Params params = 2;
    public com.xiang.proto.gym.nano.Gym.Request13002.Params params;

    public Request13002() {
      clear();
    }

    public Request13002 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request13002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.gym.nano.Gym.Request13002.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request13002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request13002(), data);
    }

    public static Request13002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request13002().mergeFrom(input);
    }
  }

  public static final class Response13002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .com.xiang.proto.DetailGym detailGym = 1;
      public com.xiang.proto.nano.Common.DetailGym detailGym;

      // repeated .com.xiang.proto.BriefUser briefUsers = 2;
      public com.xiang.proto.nano.Common.BriefUser[] briefUsers;

      public Data() {
        clear();
      }

      public Data clear() {
        detailGym = null;
        briefUsers = com.xiang.proto.nano.Common.BriefUser.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.detailGym != null) {
          output.writeMessage(1, this.detailGym);
        }
        if (this.briefUsers != null && this.briefUsers.length > 0) {
          for (int i = 0; i < this.briefUsers.length; i++) {
            com.xiang.proto.nano.Common.BriefUser element = this.briefUsers[i];
            if (element != null) {
              output.writeMessage(2, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.detailGym != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.detailGym);
        }
        if (this.briefUsers != null && this.briefUsers.length > 0) {
          for (int i = 0; i < this.briefUsers.length; i++) {
            com.xiang.proto.nano.Common.BriefUser element = this.briefUsers[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(2, element);
            }
          }
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.detailGym == null) {
                this.detailGym = new com.xiang.proto.nano.Common.DetailGym();
              }
              input.readMessage(this.detailGym);
              break;
            }
            case 18: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 18);
              int i = this.briefUsers == null ? 0 : this.briefUsers.length;
              com.xiang.proto.nano.Common.BriefUser[] newArray =
                  new com.xiang.proto.nano.Common.BriefUser[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.briefUsers, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new com.xiang.proto.nano.Common.BriefUser();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new com.xiang.proto.nano.Common.BriefUser();
              input.readMessage(newArray[i]);
              this.briefUsers = newArray;
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response13002[] _emptyArray;
    public static Response13002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response13002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.gym.Response13002.Data data = 2;
    public com.xiang.proto.gym.nano.Gym.Response13002.Data data;

    public Response13002() {
      clear();
    }

    public Response13002 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response13002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.gym.nano.Gym.Response13002.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response13002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response13002(), data);
    }

    public static Response13002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response13002().mergeFrom(input);
    }
  }

  public static final class Request13003 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional int32 gymId = 3;
      public int gymId;

      // optional float longitude = 1;
      public float longitude;

      // optional float latitude = 2;
      public float latitude;

      // optional int32 wantGymId = 4;
      public int wantGymId;

      public Params() {
        clear();
      }

      public Params clear() {
        gymId = 0;
        longitude = 0F;
        latitude = 0F;
        wantGymId = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (java.lang.Float.floatToIntBits(this.longitude)
            != java.lang.Float.floatToIntBits(0F)) {
          output.writeFloat(1, this.longitude);
        }
        if (java.lang.Float.floatToIntBits(this.latitude)
            != java.lang.Float.floatToIntBits(0F)) {
          output.writeFloat(2, this.latitude);
        }
        if (this.gymId != 0) {
          output.writeInt32(3, this.gymId);
        }
        if (this.wantGymId != 0) {
          output.writeInt32(4, this.wantGymId);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (java.lang.Float.floatToIntBits(this.longitude)
            != java.lang.Float.floatToIntBits(0F)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeFloatSize(1, this.longitude);
        }
        if (java.lang.Float.floatToIntBits(this.latitude)
            != java.lang.Float.floatToIntBits(0F)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeFloatSize(2, this.latitude);
        }
        if (this.gymId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(3, this.gymId);
        }
        if (this.wantGymId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(4, this.wantGymId);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 13: {
              this.longitude = input.readFloat();
              break;
            }
            case 21: {
              this.latitude = input.readFloat();
              break;
            }
            case 24: {
              this.gymId = input.readInt32();
              break;
            }
            case 32: {
              this.wantGymId = input.readInt32();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request13003[] _emptyArray;
    public static Request13003[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request13003[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.gym.Request13003.Params params = 2;
    public com.xiang.proto.gym.nano.Gym.Request13003.Params params;

    public Request13003() {
      clear();
    }

    public Request13003 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request13003 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.gym.nano.Gym.Request13003.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request13003 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request13003(), data);
    }

    public static Request13003 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request13003().mergeFrom(input);
    }
  }

  public static final class Response13003 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .com.xiang.proto.BriefGym briefGym = 1;
      public com.xiang.proto.nano.Common.BriefGym briefGym;

      // optional int32 userNum = 2;
      public int userNum;

      // optional int32 trendNum = 3;
      public int trendNum;

      // repeated .com.xiang.proto.BriefUser briefUsers = 4;
      public com.xiang.proto.nano.Common.BriefUser[] briefUsers;

      public Data() {
        clear();
      }

      public Data clear() {
        briefGym = null;
        userNum = 0;
        trendNum = 0;
        briefUsers = com.xiang.proto.nano.Common.BriefUser.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.briefGym != null) {
          output.writeMessage(1, this.briefGym);
        }
        if (this.userNum != 0) {
          output.writeInt32(2, this.userNum);
        }
        if (this.trendNum != 0) {
          output.writeInt32(3, this.trendNum);
        }
        if (this.briefUsers != null && this.briefUsers.length > 0) {
          for (int i = 0; i < this.briefUsers.length; i++) {
            com.xiang.proto.nano.Common.BriefUser element = this.briefUsers[i];
            if (element != null) {
              output.writeMessage(4, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.briefGym != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.briefGym);
        }
        if (this.userNum != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.userNum);
        }
        if (this.trendNum != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(3, this.trendNum);
        }
        if (this.briefUsers != null && this.briefUsers.length > 0) {
          for (int i = 0; i < this.briefUsers.length; i++) {
            com.xiang.proto.nano.Common.BriefUser element = this.briefUsers[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(4, element);
            }
          }
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.briefGym == null) {
                this.briefGym = new com.xiang.proto.nano.Common.BriefGym();
              }
              input.readMessage(this.briefGym);
              break;
            }
            case 16: {
              this.userNum = input.readInt32();
              break;
            }
            case 24: {
              this.trendNum = input.readInt32();
              break;
            }
            case 34: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 34);
              int i = this.briefUsers == null ? 0 : this.briefUsers.length;
              com.xiang.proto.nano.Common.BriefUser[] newArray =
                  new com.xiang.proto.nano.Common.BriefUser[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.briefUsers, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new com.xiang.proto.nano.Common.BriefUser();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new com.xiang.proto.nano.Common.BriefUser();
              input.readMessage(newArray[i]);
              this.briefUsers = newArray;
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response13003[] _emptyArray;
    public static Response13003[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response13003[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.gym.Response13003.Data data = 2;
    public com.xiang.proto.gym.nano.Gym.Response13003.Data data;

    public Response13003() {
      clear();
    }

    public Response13003 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response13003 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.gym.nano.Gym.Response13003.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response13003 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response13003(), data);
    }

    public static Response13003 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response13003().mergeFrom(input);
    }
  }

  public static final class Request13004 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional int32 gymId = 1;
      public int gymId;

      // optional int32 pageIndex = 2;
      public int pageIndex;

      public Params() {
        clear();
      }

      public Params clear() {
        gymId = 0;
        pageIndex = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.gymId != 0) {
          output.writeInt32(1, this.gymId);
        }
        if (this.pageIndex != 0) {
          output.writeInt32(2, this.pageIndex);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.gymId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, this.gymId);
        }
        if (this.pageIndex != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.pageIndex);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.gymId = input.readInt32();
              break;
            }
            case 16: {
              this.pageIndex = input.readInt32();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request13004[] _emptyArray;
    public static Request13004[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request13004[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.gym.Request13004.Params params = 2;
    public com.xiang.proto.gym.nano.Gym.Request13004.Params params;

    public Request13004() {
      clear();
    }

    public Request13004 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request13004 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.gym.nano.Gym.Request13004.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request13004 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request13004(), data);
    }

    public static Request13004 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request13004().mergeFrom(input);
    }
  }

  public static final class Response13004 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .com.xiang.proto.Trend trends = 1;
      public com.xiang.proto.nano.Common.Trend[] trends;

      // optional int32 maxCountPerPage = 2;
      public int maxCountPerPage;

      public Data() {
        clear();
      }

      public Data clear() {
        trends = com.xiang.proto.nano.Common.Trend.emptyArray();
        maxCountPerPage = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.trends != null && this.trends.length > 0) {
          for (int i = 0; i < this.trends.length; i++) {
            com.xiang.proto.nano.Common.Trend element = this.trends[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        if (this.maxCountPerPage != 0) {
          output.writeInt32(2, this.maxCountPerPage);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.trends != null && this.trends.length > 0) {
          for (int i = 0; i < this.trends.length; i++) {
            com.xiang.proto.nano.Common.Trend element = this.trends[i];
            if (element != null) {
              size += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        if (this.maxCountPerPage != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.maxCountPerPage);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.trends == null ? 0 : this.trends.length;
              com.xiang.proto.nano.Common.Trend[] newArray =
                  new com.xiang.proto.nano.Common.Trend[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.trends, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new com.xiang.proto.nano.Common.Trend();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new com.xiang.proto.nano.Common.Trend();
              input.readMessage(newArray[i]);
              this.trends = newArray;
              break;
            }
            case 16: {
              this.maxCountPerPage = input.readInt32();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response13004[] _emptyArray;
    public static Response13004[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response13004[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.gym.Response13004.Data data = 2;
    public com.xiang.proto.gym.nano.Gym.Response13004.Data data;

    public Response13004() {
      clear();
    }

    public Response13004 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response13004 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.gym.nano.Gym.Response13004.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response13004 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response13004(), data);
    }

    public static Response13004 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response13004().mergeFrom(input);
    }
  }
}
