// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.xiang.proto.nano;

@SuppressWarnings("hiding")
public interface Common {

  // enum CardType
  public static final int Once = 0;
  public static final int Month = 1;
  public static final int Quarter = 2;

  // enum EquipmentType
  public static final int PAO_BU_JI = 0;
  public static final int LIN_YU_FANG = 1;

  // enum Sex
  public static final int MALE = 0;
  public static final int FEMALE = 1;

  public static final class RequestCommon extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RequestCommon[] _emptyArray;
    public static RequestCommon[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RequestCommon[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 userid = 1;
    public int userid;

    // optional string userkey = 2;
    public java.lang.String userkey;

    // optional int32 cmdid = 3;
    public int cmdid;

    // optional int64 timestamp = 4;
    public long timestamp;

    // optional string version = 5;
    public java.lang.String version;

    // optional int32 platform = 6;
    public int platform;

    public RequestCommon() {
      clear();
    }

    public RequestCommon clear() {
      userid = 0;
      userkey = "";
      cmdid = 0;
      timestamp = 0L;
      version = "";
      platform = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.userid != 0) {
        output.writeInt32(1, this.userid);
      }
      if (!this.userkey.equals("")) {
        output.writeString(2, this.userkey);
      }
      if (this.cmdid != 0) {
        output.writeInt32(3, this.cmdid);
      }
      if (this.timestamp != 0L) {
        output.writeInt64(4, this.timestamp);
      }
      if (!this.version.equals("")) {
        output.writeString(5, this.version);
      }
      if (this.platform != 0) {
        output.writeInt32(6, this.platform);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.userid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.userid);
      }
      if (!this.userkey.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.userkey);
      }
      if (this.cmdid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.cmdid);
      }
      if (this.timestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.timestamp);
      }
      if (!this.version.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.version);
      }
      if (this.platform != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.platform);
      }
      return size;
    }

    @Override
    public RequestCommon mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userid = input.readInt32();
            break;
          }
          case 18: {
            this.userkey = input.readString();
            break;
          }
          case 24: {
            this.cmdid = input.readInt32();
            break;
          }
          case 32: {
            this.timestamp = input.readInt64();
            break;
          }
          case 42: {
            this.version = input.readString();
            break;
          }
          case 48: {
            this.platform = input.readInt32();
            break;
          }
        }
      }
    }

    public static RequestCommon parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RequestCommon(), data);
    }

    public static RequestCommon parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RequestCommon().mergeFrom(input);
    }
  }

  public static final class ResponseCommon extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ResponseCommon[] _emptyArray;
    public static ResponseCommon[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ResponseCommon[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 code = 1;
    public int code;

    // optional string message = 2;
    public java.lang.String message;

    // optional int32 cmdid = 3;
    public int cmdid;

    // optional int64 timestamp = 4;
    public long timestamp;

    // optional int32 userid = 5;
    public int userid;

    public ResponseCommon() {
      clear();
    }

    public ResponseCommon clear() {
      code = 0;
      message = "";
      cmdid = 0;
      timestamp = 0L;
      userid = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.code != 0) {
        output.writeInt32(1, this.code);
      }
      if (!this.message.equals("")) {
        output.writeString(2, this.message);
      }
      if (this.cmdid != 0) {
        output.writeInt32(3, this.cmdid);
      }
      if (this.timestamp != 0L) {
        output.writeInt64(4, this.timestamp);
      }
      if (this.userid != 0) {
        output.writeInt32(5, this.userid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.code != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.code);
      }
      if (!this.message.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.message);
      }
      if (this.cmdid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.cmdid);
      }
      if (this.timestamp != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.timestamp);
      }
      if (this.userid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.userid);
      }
      return size;
    }

    @Override
    public ResponseCommon mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.code = input.readInt32();
            break;
          }
          case 18: {
            this.message = input.readString();
            break;
          }
          case 24: {
            this.cmdid = input.readInt32();
            break;
          }
          case 32: {
            this.timestamp = input.readInt64();
            break;
          }
          case 40: {
            this.userid = input.readInt32();
            break;
          }
        }
      }
    }

    public static ResponseCommon parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ResponseCommon(), data);
    }

    public static ResponseCommon parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ResponseCommon().mergeFrom(input);
    }
  }

  public static final class Trend extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Trend[] _emptyArray;
    public static Trend[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Trend[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 id = 1;
    public int id;

    // optional .com.xiang.proto.BriefUser briefUser = 2;
    public com.xiang.proto.nano.Common.BriefUser briefUser;

    // optional int64 createTime = 3;
    public long createTime;

    // optional int32 gymId = 4;
    public int gymId;

    // optional string gymName = 5;
    public java.lang.String gymName;

    // optional string content = 6;
    public java.lang.String content;

    // repeated string imgs = 7;
    public java.lang.String[] imgs;

    // optional int32 likeCount = 8;
    public int likeCount;

    // optional int32 commentCount = 9;
    public int commentCount;

    // optional bool isLiked = 10;
    public boolean isLiked;

    public Trend() {
      clear();
    }

    public Trend clear() {
      id = 0;
      briefUser = null;
      createTime = 0L;
      gymId = 0;
      gymName = "";
      content = "";
      imgs = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      likeCount = 0;
      commentCount = 0;
      isLiked = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0) {
        output.writeInt32(1, this.id);
      }
      if (this.briefUser != null) {
        output.writeMessage(2, this.briefUser);
      }
      if (this.createTime != 0L) {
        output.writeInt64(3, this.createTime);
      }
      if (this.gymId != 0) {
        output.writeInt32(4, this.gymId);
      }
      if (!this.gymName.equals("")) {
        output.writeString(5, this.gymName);
      }
      if (!this.content.equals("")) {
        output.writeString(6, this.content);
      }
      if (this.imgs != null && this.imgs.length > 0) {
        for (int i = 0; i < this.imgs.length; i++) {
          java.lang.String element = this.imgs[i];
          if (element != null) {
            output.writeString(7, element);
          }
        }
      }
      if (this.likeCount != 0) {
        output.writeInt32(8, this.likeCount);
      }
      if (this.commentCount != 0) {
        output.writeInt32(9, this.commentCount);
      }
      if (this.isLiked != false) {
        output.writeBool(10, this.isLiked);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.id);
      }
      if (this.briefUser != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.briefUser);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.createTime);
      }
      if (this.gymId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.gymId);
      }
      if (!this.gymName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.gymName);
      }
      if (!this.content.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.content);
      }
      if (this.imgs != null && this.imgs.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.imgs.length; i++) {
          java.lang.String element = this.imgs[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (this.likeCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(8, this.likeCount);
      }
      if (this.commentCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.commentCount);
      }
      if (this.isLiked != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(10, this.isLiked);
      }
      return size;
    }

    @Override
    public Trend mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            if (this.briefUser == null) {
              this.briefUser = new com.xiang.proto.nano.Common.BriefUser();
            }
            input.readMessage(this.briefUser);
            break;
          }
          case 24: {
            this.createTime = input.readInt64();
            break;
          }
          case 32: {
            this.gymId = input.readInt32();
            break;
          }
          case 42: {
            this.gymName = input.readString();
            break;
          }
          case 50: {
            this.content = input.readString();
            break;
          }
          case 58: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 58);
            int i = this.imgs == null ? 0 : this.imgs.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.imgs, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.imgs = newArray;
            break;
          }
          case 64: {
            this.likeCount = input.readInt32();
            break;
          }
          case 72: {
            this.commentCount = input.readInt32();
            break;
          }
          case 80: {
            this.isLiked = input.readBool();
            break;
          }
        }
      }
    }

    public static Trend parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Trend(), data);
    }

    public static Trend parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Trend().mergeFrom(input);
    }
  }

  public static final class Banner extends
      com.google.protobuf.nano.MessageNano {

    // enum BannerType
    public static final int URL = 0;
    public static final int TREND = 1;
    public static final int USER = 2;

    private static volatile Banner[] _emptyArray;
    public static Banner[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Banner[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 id = 1;
    public int id;

    // optional string coverUrl = 2;
    public java.lang.String coverUrl;

    // optional .com.xiang.proto.Banner.BannerType type = 3;
    public int type;

    // optional string webUrl = 4;
    public java.lang.String webUrl;

    // optional int32 trendId = 5;
    public int trendId;

    // optional int32 userId = 6;
    public int userId;

    public Banner() {
      clear();
    }

    public Banner clear() {
      id = 0;
      coverUrl = "";
      type = com.xiang.proto.nano.Common.Banner.URL;
      webUrl = "";
      trendId = 0;
      userId = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0) {
        output.writeInt32(1, this.id);
      }
      if (!this.coverUrl.equals("")) {
        output.writeString(2, this.coverUrl);
      }
      if (this.type != com.xiang.proto.nano.Common.Banner.URL) {
        output.writeInt32(3, this.type);
      }
      if (!this.webUrl.equals("")) {
        output.writeString(4, this.webUrl);
      }
      if (this.trendId != 0) {
        output.writeInt32(5, this.trendId);
      }
      if (this.userId != 0) {
        output.writeInt32(6, this.userId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.id);
      }
      if (!this.coverUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.coverUrl);
      }
      if (this.type != com.xiang.proto.nano.Common.Banner.URL) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.type);
      }
      if (!this.webUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.webUrl);
      }
      if (this.trendId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.trendId);
      }
      if (this.userId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.userId);
      }
      return size;
    }

    @Override
    public Banner mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            this.coverUrl = input.readString();
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case com.xiang.proto.nano.Common.Banner.URL:
              case com.xiang.proto.nano.Common.Banner.TREND:
              case com.xiang.proto.nano.Common.Banner.USER:
                this.type = value;
                break;
            }
            break;
          }
          case 34: {
            this.webUrl = input.readString();
            break;
          }
          case 40: {
            this.trendId = input.readInt32();
            break;
          }
          case 48: {
            this.userId = input.readInt32();
            break;
          }
        }
      }
    }

    public static Banner parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Banner(), data);
    }

    public static Banner parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Banner().mergeFrom(input);
    }
  }

  public static final class BriefUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BriefUser[] _emptyArray;
    public static BriefUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BriefUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 userId = 1;
    public int userId;

    // optional string userName = 2;
    public java.lang.String userName;

    // optional string userAvatar = 3;
    public java.lang.String userAvatar;

    public BriefUser() {
      clear();
    }

    public BriefUser clear() {
      userId = 0;
      userName = "";
      userAvatar = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.userId != 0) {
        output.writeInt32(1, this.userId);
      }
      if (!this.userName.equals("")) {
        output.writeString(2, this.userName);
      }
      if (!this.userAvatar.equals("")) {
        output.writeString(3, this.userAvatar);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.userId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.userId);
      }
      if (!this.userName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.userName);
      }
      if (!this.userAvatar.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.userAvatar);
      }
      return size;
    }

    @Override
    public BriefUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readInt32();
            break;
          }
          case 18: {
            this.userName = input.readString();
            break;
          }
          case 26: {
            this.userAvatar = input.readString();
            break;
          }
        }
      }
    }

    public static BriefUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BriefUser(), data);
    }

    public static BriefUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BriefUser().mergeFrom(input);
    }
  }

  public static final class BriefGym extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BriefGym[] _emptyArray;
    public static BriefGym[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BriefGym[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 id = 1;
    public int id;

    // optional string gymName = 2;
    public java.lang.String gymName;

    // repeated string gymCover = 3;
    public java.lang.String[] gymCover;

    // optional string place = 4;
    public java.lang.String place;

    // optional string gymAvatar = 8;
    public java.lang.String gymAvatar;

    // optional float latitude = 5;
    public float latitude;

    // optional float longitude = 6;
    public float longitude;

    // optional bool isCoop = 7;
    public boolean isCoop;

    public BriefGym() {
      clear();
    }

    public BriefGym clear() {
      id = 0;
      gymName = "";
      gymCover = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      place = "";
      gymAvatar = "";
      latitude = 0F;
      longitude = 0F;
      isCoop = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0) {
        output.writeInt32(1, this.id);
      }
      if (!this.gymName.equals("")) {
        output.writeString(2, this.gymName);
      }
      if (this.gymCover != null && this.gymCover.length > 0) {
        for (int i = 0; i < this.gymCover.length; i++) {
          java.lang.String element = this.gymCover[i];
          if (element != null) {
            output.writeString(3, element);
          }
        }
      }
      if (!this.place.equals("")) {
        output.writeString(4, this.place);
      }
      if (java.lang.Float.floatToIntBits(this.latitude)
          != java.lang.Float.floatToIntBits(0F)) {
        output.writeFloat(5, this.latitude);
      }
      if (java.lang.Float.floatToIntBits(this.longitude)
          != java.lang.Float.floatToIntBits(0F)) {
        output.writeFloat(6, this.longitude);
      }
      if (this.isCoop != false) {
        output.writeBool(7, this.isCoop);
      }
      if (!this.gymAvatar.equals("")) {
        output.writeString(8, this.gymAvatar);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.id);
      }
      if (!this.gymName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.gymName);
      }
      if (this.gymCover != null && this.gymCover.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.gymCover.length; i++) {
          java.lang.String element = this.gymCover[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (!this.place.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.place);
      }
      if (java.lang.Float.floatToIntBits(this.latitude)
          != java.lang.Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(5, this.latitude);
      }
      if (java.lang.Float.floatToIntBits(this.longitude)
          != java.lang.Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(6, this.longitude);
      }
      if (this.isCoop != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(7, this.isCoop);
      }
      if (!this.gymAvatar.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.gymAvatar);
      }
      return size;
    }

    @Override
    public BriefGym mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            this.gymName = input.readString();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.gymCover == null ? 0 : this.gymCover.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.gymCover, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.gymCover = newArray;
            break;
          }
          case 34: {
            this.place = input.readString();
            break;
          }
          case 45: {
            this.latitude = input.readFloat();
            break;
          }
          case 53: {
            this.longitude = input.readFloat();
            break;
          }
          case 56: {
            this.isCoop = input.readBool();
            break;
          }
          case 66: {
            this.gymAvatar = input.readString();
            break;
          }
        }
      }
    }

    public static BriefGym parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BriefGym(), data);
    }

    public static BriefGym parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BriefGym().mergeFrom(input);
    }
  }

  public static final class DetailGym extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DetailGym[] _emptyArray;
    public static DetailGym[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DetailGym[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.BriefGym briefGym = 1;
    public com.xiang.proto.nano.Common.BriefGym briefGym;

    // repeated .com.xiang.proto.Equipment equipments = 2;
    public com.xiang.proto.nano.Common.Equipment[] equipments;

    // repeated .com.xiang.proto.Course courses = 3;
    public com.xiang.proto.nano.Common.Course[] courses;

    // repeated .com.xiang.proto.GymCard gymCards = 4;
    public com.xiang.proto.nano.Common.GymCard[] gymCards;

    public DetailGym() {
      clear();
    }

    public DetailGym clear() {
      briefGym = null;
      equipments = com.xiang.proto.nano.Common.Equipment.emptyArray();
      courses = com.xiang.proto.nano.Common.Course.emptyArray();
      gymCards = com.xiang.proto.nano.Common.GymCard.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.briefGym != null) {
        output.writeMessage(1, this.briefGym);
      }
      if (this.equipments != null && this.equipments.length > 0) {
        for (int i = 0; i < this.equipments.length; i++) {
          com.xiang.proto.nano.Common.Equipment element = this.equipments[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.courses != null && this.courses.length > 0) {
        for (int i = 0; i < this.courses.length; i++) {
          com.xiang.proto.nano.Common.Course element = this.courses[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.gymCards != null && this.gymCards.length > 0) {
        for (int i = 0; i < this.gymCards.length; i++) {
          com.xiang.proto.nano.Common.GymCard element = this.gymCards[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.briefGym != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.briefGym);
      }
      if (this.equipments != null && this.equipments.length > 0) {
        for (int i = 0; i < this.equipments.length; i++) {
          com.xiang.proto.nano.Common.Equipment element = this.equipments[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.courses != null && this.courses.length > 0) {
        for (int i = 0; i < this.courses.length; i++) {
          com.xiang.proto.nano.Common.Course element = this.courses[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.gymCards != null && this.gymCards.length > 0) {
        for (int i = 0; i < this.gymCards.length; i++) {
          com.xiang.proto.nano.Common.GymCard element = this.gymCards[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }

    @Override
    public DetailGym mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.briefGym == null) {
              this.briefGym = new com.xiang.proto.nano.Common.BriefGym();
            }
            input.readMessage(this.briefGym);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.equipments == null ? 0 : this.equipments.length;
            com.xiang.proto.nano.Common.Equipment[] newArray =
                new com.xiang.proto.nano.Common.Equipment[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.equipments, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.xiang.proto.nano.Common.Equipment();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.xiang.proto.nano.Common.Equipment();
            input.readMessage(newArray[i]);
            this.equipments = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.courses == null ? 0 : this.courses.length;
            com.xiang.proto.nano.Common.Course[] newArray =
                new com.xiang.proto.nano.Common.Course[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.courses, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.xiang.proto.nano.Common.Course();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.xiang.proto.nano.Common.Course();
            input.readMessage(newArray[i]);
            this.courses = newArray;
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.gymCards == null ? 0 : this.gymCards.length;
            com.xiang.proto.nano.Common.GymCard[] newArray =
                new com.xiang.proto.nano.Common.GymCard[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.gymCards, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.xiang.proto.nano.Common.GymCard();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.xiang.proto.nano.Common.GymCard();
            input.readMessage(newArray[i]);
            this.gymCards = newArray;
            break;
          }
        }
      }
    }

    public static DetailGym parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DetailGym(), data);
    }

    public static DetailGym parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DetailGym().mergeFrom(input);
    }
  }

  public static final class Equipment extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Equipment[] _emptyArray;
    public static Equipment[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Equipment[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string name = 1;
    public java.lang.String name;

    // optional int32 count = 2;
    public int count;

    // optional .com.xiang.proto.EquipmentType equipmentType = 3;
    public int equipmentType;

    public Equipment() {
      clear();
    }

    public Equipment clear() {
      name = "";
      count = 0;
      equipmentType = com.xiang.proto.nano.Common.PAO_BU_JI;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.name.equals("")) {
        output.writeString(1, this.name);
      }
      if (this.count != 0) {
        output.writeInt32(2, this.count);
      }
      if (this.equipmentType != com.xiang.proto.nano.Common.PAO_BU_JI) {
        output.writeInt32(3, this.equipmentType);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.name);
      }
      if (this.count != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.count);
      }
      if (this.equipmentType != com.xiang.proto.nano.Common.PAO_BU_JI) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.equipmentType);
      }
      return size;
    }

    @Override
    public Equipment mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
          case 16: {
            this.count = input.readInt32();
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case com.xiang.proto.nano.Common.PAO_BU_JI:
              case com.xiang.proto.nano.Common.LIN_YU_FANG:
                this.equipmentType = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static Equipment parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Equipment(), data);
    }

    public static Equipment parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Equipment().mergeFrom(input);
    }
  }

  public static final class Course extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Course[] _emptyArray;
    public static Course[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Course[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string name = 1;
    public java.lang.String name;

    // optional int32 week = 2;
    public int week;

    // optional .com.xiang.proto.CourseTime courseTime = 3;
    public com.xiang.proto.nano.Common.CourseTime courseTime;

    public Course() {
      clear();
    }

    public Course clear() {
      name = "";
      week = 0;
      courseTime = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.name.equals("")) {
        output.writeString(1, this.name);
      }
      if (this.week != 0) {
        output.writeInt32(2, this.week);
      }
      if (this.courseTime != null) {
        output.writeMessage(3, this.courseTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.name);
      }
      if (this.week != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.week);
      }
      if (this.courseTime != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.courseTime);
      }
      return size;
    }

    @Override
    public Course mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
          case 16: {
            this.week = input.readInt32();
            break;
          }
          case 26: {
            if (this.courseTime == null) {
              this.courseTime = new com.xiang.proto.nano.Common.CourseTime();
            }
            input.readMessage(this.courseTime);
            break;
          }
        }
      }
    }

    public static Course parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Course(), data);
    }

    public static Course parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Course().mergeFrom(input);
    }
  }

  public static final class CourseTime extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CourseTime[] _emptyArray;
    public static CourseTime[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CourseTime[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 fromHour = 1;
    public int fromHour;

    // optional int32 fromMinite = 2;
    public int fromMinite;

    // optional int32 toHour = 3;
    public int toHour;

    // optional int32 toMinite = 4;
    public int toMinite;

    public CourseTime() {
      clear();
    }

    public CourseTime clear() {
      fromHour = 0;
      fromMinite = 0;
      toHour = 0;
      toMinite = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.fromHour != 0) {
        output.writeInt32(1, this.fromHour);
      }
      if (this.fromMinite != 0) {
        output.writeInt32(2, this.fromMinite);
      }
      if (this.toHour != 0) {
        output.writeInt32(3, this.toHour);
      }
      if (this.toMinite != 0) {
        output.writeInt32(4, this.toMinite);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.fromHour != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.fromHour);
      }
      if (this.fromMinite != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.fromMinite);
      }
      if (this.toHour != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.toHour);
      }
      if (this.toMinite != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.toMinite);
      }
      return size;
    }

    @Override
    public CourseTime mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.fromHour = input.readInt32();
            break;
          }
          case 16: {
            this.fromMinite = input.readInt32();
            break;
          }
          case 24: {
            this.toHour = input.readInt32();
            break;
          }
          case 32: {
            this.toMinite = input.readInt32();
            break;
          }
        }
      }
    }

    public static CourseTime parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CourseTime(), data);
    }

    public static CourseTime parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CourseTime().mergeFrom(input);
    }
  }

  public static final class GymCard extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GymCard[] _emptyArray;
    public static GymCard[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GymCard[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.CardType cardType = 1;
    public int cardType;

    // optional float price = 2;
    public float price;

    public GymCard() {
      clear();
    }

    public GymCard clear() {
      cardType = com.xiang.proto.nano.Common.Once;
      price = 0F;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.cardType != com.xiang.proto.nano.Common.Once) {
        output.writeInt32(1, this.cardType);
      }
      if (java.lang.Float.floatToIntBits(this.price)
          != java.lang.Float.floatToIntBits(0F)) {
        output.writeFloat(2, this.price);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.cardType != com.xiang.proto.nano.Common.Once) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.cardType);
      }
      if (java.lang.Float.floatToIntBits(this.price)
          != java.lang.Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(2, this.price);
      }
      return size;
    }

    @Override
    public GymCard mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case com.xiang.proto.nano.Common.Once:
              case com.xiang.proto.nano.Common.Month:
              case com.xiang.proto.nano.Common.Quarter:
                this.cardType = value;
                break;
            }
            break;
          }
          case 21: {
            this.price = input.readFloat();
            break;
          }
        }
      }
    }

    public static GymCard parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GymCard(), data);
    }

    public static GymCard parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GymCard().mergeFrom(input);
    }
  }

  public static final class CommentMessage extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CommentMessage[] _emptyArray;
    public static CommentMessage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CommentMessage[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 messageId = 1;
    public int messageId;

    // optional string messageContent = 2;
    public java.lang.String messageContent;

    // optional string avatar = 3;
    public java.lang.String avatar;

    // optional int64 createTime = 4;
    public long createTime;

    // optional int32 trendId = 5;
    public int trendId;

    public CommentMessage() {
      clear();
    }

    public CommentMessage clear() {
      messageId = 0;
      messageContent = "";
      avatar = "";
      createTime = 0L;
      trendId = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.messageId != 0) {
        output.writeInt32(1, this.messageId);
      }
      if (!this.messageContent.equals("")) {
        output.writeString(2, this.messageContent);
      }
      if (!this.avatar.equals("")) {
        output.writeString(3, this.avatar);
      }
      if (this.createTime != 0L) {
        output.writeInt64(4, this.createTime);
      }
      if (this.trendId != 0) {
        output.writeInt32(5, this.trendId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.messageId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.messageId);
      }
      if (!this.messageContent.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.messageContent);
      }
      if (!this.avatar.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.avatar);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.createTime);
      }
      if (this.trendId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.trendId);
      }
      return size;
    }

    @Override
    public CommentMessage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.messageId = input.readInt32();
            break;
          }
          case 18: {
            this.messageContent = input.readString();
            break;
          }
          case 26: {
            this.avatar = input.readString();
            break;
          }
          case 32: {
            this.createTime = input.readInt64();
            break;
          }
          case 40: {
            this.trendId = input.readInt32();
            break;
          }
        }
      }
    }

    public static CommentMessage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CommentMessage(), data);
    }

    public static CommentMessage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CommentMessage().mergeFrom(input);
    }
  }

  public static final class Comment extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Comment[] _emptyArray;
    public static Comment[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Comment[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.BriefUser briefUser = 1;
    public com.xiang.proto.nano.Common.BriefUser briefUser;

    // optional int32 commentId = 2;
    public int commentId;

    // optional string commentContent = 3;
    public java.lang.String commentContent;

    // optional int32 trendId = 4;
    public int trendId;

    // optional int32 toUserid = 5;
    public int toUserid;

    // optional string toUserName = 6;
    public java.lang.String toUserName;

    // optional int64 createTime = 7;
    public long createTime;

    // optional string gymName = 8;
    public java.lang.String gymName;

    public Comment() {
      clear();
    }

    public Comment clear() {
      briefUser = null;
      commentId = 0;
      commentContent = "";
      trendId = 0;
      toUserid = 0;
      toUserName = "";
      createTime = 0L;
      gymName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.briefUser != null) {
        output.writeMessage(1, this.briefUser);
      }
      if (this.commentId != 0) {
        output.writeInt32(2, this.commentId);
      }
      if (!this.commentContent.equals("")) {
        output.writeString(3, this.commentContent);
      }
      if (this.trendId != 0) {
        output.writeInt32(4, this.trendId);
      }
      if (this.toUserid != 0) {
        output.writeInt32(5, this.toUserid);
      }
      if (!this.toUserName.equals("")) {
        output.writeString(6, this.toUserName);
      }
      if (this.createTime != 0L) {
        output.writeInt64(7, this.createTime);
      }
      if (!this.gymName.equals("")) {
        output.writeString(8, this.gymName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.briefUser != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.briefUser);
      }
      if (this.commentId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.commentId);
      }
      if (!this.commentContent.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.commentContent);
      }
      if (this.trendId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.trendId);
      }
      if (this.toUserid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.toUserid);
      }
      if (!this.toUserName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.toUserName);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(7, this.createTime);
      }
      if (!this.gymName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.gymName);
      }
      return size;
    }

    @Override
    public Comment mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.briefUser == null) {
              this.briefUser = new com.xiang.proto.nano.Common.BriefUser();
            }
            input.readMessage(this.briefUser);
            break;
          }
          case 16: {
            this.commentId = input.readInt32();
            break;
          }
          case 26: {
            this.commentContent = input.readString();
            break;
          }
          case 32: {
            this.trendId = input.readInt32();
            break;
          }
          case 40: {
            this.toUserid = input.readInt32();
            break;
          }
          case 50: {
            this.toUserName = input.readString();
            break;
          }
          case 56: {
            this.createTime = input.readInt64();
            break;
          }
          case 66: {
            this.gymName = input.readString();
            break;
          }
        }
      }
    }

    public static Comment parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Comment(), data);
    }

    public static Comment parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Comment().mergeFrom(input);
    }
  }

  public static final class TrendBriefMessage extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TrendBriefMessage[] _emptyArray;
    public static TrendBriefMessage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TrendBriefMessage[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string lastAvatar = 1;
    public java.lang.String lastAvatar;

    // optional int32 count = 2;
    public int count;

    public TrendBriefMessage() {
      clear();
    }

    public TrendBriefMessage clear() {
      lastAvatar = "";
      count = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.lastAvatar.equals("")) {
        output.writeString(1, this.lastAvatar);
      }
      if (this.count != 0) {
        output.writeInt32(2, this.count);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.lastAvatar.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.lastAvatar);
      }
      if (this.count != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.count);
      }
      return size;
    }

    @Override
    public TrendBriefMessage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.lastAvatar = input.readString();
            break;
          }
          case 16: {
            this.count = input.readInt32();
            break;
          }
        }
      }
    }

    public static TrendBriefMessage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TrendBriefMessage(), data);
    }

    public static TrendBriefMessage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TrendBriefMessage().mergeFrom(input);
    }
  }

  public static final class DetailUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DetailUser[] _emptyArray;
    public static DetailUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DetailUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 userId = 1;
    public int userId;

    // optional string userName = 2;
    public java.lang.String userName;

    // optional string userAvatar = 3;
    public java.lang.String userAvatar;

    // optional .com.xiang.proto.Sex sex = 4;
    public int sex;

    // optional string sign = 5;
    public java.lang.String sign;

    // repeated .com.xiang.proto.Trend trends = 6;
    public com.xiang.proto.nano.Common.Trend[] trends;

    // optional bool isFollowed = 7;
    public boolean isFollowed;

    // optional int32 guanzhuCount = 8;
    public int guanzhuCount;

    // optional int32 fensiCount = 9;
    public int fensiCount;

    // optional int32 trendCount = 10;
    public int trendCount;

    public DetailUser() {
      clear();
    }

    public DetailUser clear() {
      userId = 0;
      userName = "";
      userAvatar = "";
      sex = com.xiang.proto.nano.Common.MALE;
      sign = "";
      trends = com.xiang.proto.nano.Common.Trend.emptyArray();
      isFollowed = false;
      guanzhuCount = 0;
      fensiCount = 0;
      trendCount = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.userId != 0) {
        output.writeInt32(1, this.userId);
      }
      if (!this.userName.equals("")) {
        output.writeString(2, this.userName);
      }
      if (!this.userAvatar.equals("")) {
        output.writeString(3, this.userAvatar);
      }
      if (this.sex != com.xiang.proto.nano.Common.MALE) {
        output.writeInt32(4, this.sex);
      }
      if (!this.sign.equals("")) {
        output.writeString(5, this.sign);
      }
      if (this.trends != null && this.trends.length > 0) {
        for (int i = 0; i < this.trends.length; i++) {
          com.xiang.proto.nano.Common.Trend element = this.trends[i];
          if (element != null) {
            output.writeMessage(6, element);
          }
        }
      }
      if (this.isFollowed != false) {
        output.writeBool(7, this.isFollowed);
      }
      if (this.guanzhuCount != 0) {
        output.writeInt32(8, this.guanzhuCount);
      }
      if (this.fensiCount != 0) {
        output.writeInt32(9, this.fensiCount);
      }
      if (this.trendCount != 0) {
        output.writeInt32(10, this.trendCount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.userId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.userId);
      }
      if (!this.userName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.userName);
      }
      if (!this.userAvatar.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.userAvatar);
      }
      if (this.sex != com.xiang.proto.nano.Common.MALE) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(4, this.sex);
      }
      if (!this.sign.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.sign);
      }
      if (this.trends != null && this.trends.length > 0) {
        for (int i = 0; i < this.trends.length; i++) {
          com.xiang.proto.nano.Common.Trend element = this.trends[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(6, element);
          }
        }
      }
      if (this.isFollowed != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(7, this.isFollowed);
      }
      if (this.guanzhuCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(8, this.guanzhuCount);
      }
      if (this.fensiCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.fensiCount);
      }
      if (this.trendCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.trendCount);
      }
      return size;
    }

    @Override
    public DetailUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readInt32();
            break;
          }
          case 18: {
            this.userName = input.readString();
            break;
          }
          case 26: {
            this.userAvatar = input.readString();
            break;
          }
          case 32: {
            int value = input.readInt32();
            switch (value) {
              case com.xiang.proto.nano.Common.MALE:
              case com.xiang.proto.nano.Common.FEMALE:
                this.sex = value;
                break;
            }
            break;
          }
          case 42: {
            this.sign = input.readString();
            break;
          }
          case 50: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 50);
            int i = this.trends == null ? 0 : this.trends.length;
            com.xiang.proto.nano.Common.Trend[] newArray =
                new com.xiang.proto.nano.Common.Trend[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.trends, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.xiang.proto.nano.Common.Trend();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.xiang.proto.nano.Common.Trend();
            input.readMessage(newArray[i]);
            this.trends = newArray;
            break;
          }
          case 56: {
            this.isFollowed = input.readBool();
            break;
          }
          case 64: {
            this.guanzhuCount = input.readInt32();
            break;
          }
          case 72: {
            this.fensiCount = input.readInt32();
            break;
          }
          case 80: {
            this.trendCount = input.readInt32();
            break;
          }
        }
      }
    }

    public static DetailUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DetailUser(), data);
    }

    public static DetailUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DetailUser().mergeFrom(input);
    }
  }

  public static final class SearchedUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SearchedUser[] _emptyArray;
    public static SearchedUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SearchedUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 userId = 1;
    public int userId;

    // optional string userName = 2;
    public java.lang.String userName;

    // optional string userAvatar = 3;
    public java.lang.String userAvatar;

    // optional string sign = 4;
    public java.lang.String sign;

    // repeated string images = 5;
    public java.lang.String[] images;

    public SearchedUser() {
      clear();
    }

    public SearchedUser clear() {
      userId = 0;
      userName = "";
      userAvatar = "";
      sign = "";
      images = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.userId != 0) {
        output.writeInt32(1, this.userId);
      }
      if (!this.userName.equals("")) {
        output.writeString(2, this.userName);
      }
      if (!this.userAvatar.equals("")) {
        output.writeString(3, this.userAvatar);
      }
      if (!this.sign.equals("")) {
        output.writeString(4, this.sign);
      }
      if (this.images != null && this.images.length > 0) {
        for (int i = 0; i < this.images.length; i++) {
          java.lang.String element = this.images[i];
          if (element != null) {
            output.writeString(5, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.userId != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.userId);
      }
      if (!this.userName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.userName);
      }
      if (!this.userAvatar.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.userAvatar);
      }
      if (!this.sign.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.sign);
      }
      if (this.images != null && this.images.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.images.length; i++) {
          java.lang.String element = this.images[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public SearchedUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readInt32();
            break;
          }
          case 18: {
            this.userName = input.readString();
            break;
          }
          case 26: {
            this.userAvatar = input.readString();
            break;
          }
          case 34: {
            this.sign = input.readString();
            break;
          }
          case 42: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.images == null ? 0 : this.images.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.images, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.images = newArray;
            break;
          }
        }
      }
    }

    public static SearchedUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SearchedUser(), data);
    }

    public static SearchedUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SearchedUser().mergeFrom(input);
    }
  }
}
