// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gym.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BriefGym;
@class BriefUser;
@class DetailGym;
@class Request13001_Params;
@class Request13002_Params;
@class Request13003_Params;
@class Request13004_Params;
@class RequestCommon;
@class Response13001_Data;
@class Response13002_Data;
@class Response13003_Data;
@class Response13004_Data;
@class ResponseCommon;
@class Trend;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GymRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface GymRoot : GPBRootObject
@end

#pragma mark - Request13001

typedef GPB_ENUM(Request13001_FieldNumber) {
  Request13001_FieldNumber_Common = 1,
  Request13001_FieldNumber_Params = 2,
};

/// 获取附近健身房列表
/// /gym/getGymList
@interface Request13001 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Request13001_Params *params;
/// Test to see if @c params has been set.
@property(nonatomic, readwrite) BOOL hasParams;

@end

#pragma mark - Request13001_Params

typedef GPB_ENUM(Request13001_Params_FieldNumber) {
  Request13001_Params_FieldNumber_Longitude = 1,
  Request13001_Params_FieldNumber_Latitude = 2,
  Request13001_Params_FieldNumber_PageIndex = 3,
};

@interface Request13001_Params : GPBMessage

@property(nonatomic, readwrite) float longitude;

@property(nonatomic, readwrite) float latitude;

/// 从第0页开始
@property(nonatomic, readwrite) int32_t pageIndex;

@end

#pragma mark - Response13001

typedef GPB_ENUM(Response13001_FieldNumber) {
  Response13001_FieldNumber_Common = 1,
  Response13001_FieldNumber_Data_p = 2,
};

@interface Response13001 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Response13001_Data *data_p;
/// Test to see if @c data_p has been set.
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - Response13001_Data

typedef GPB_ENUM(Response13001_Data_FieldNumber) {
  Response13001_Data_FieldNumber_BriefGymsArray = 1,
  Response13001_Data_FieldNumber_MaxCountPerPage = 2,
};

@interface Response13001_Data : GPBMessage

/// 如果列表为空，data可能为null，客户端做好判空准备
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BriefGym*> *briefGymsArray;
/// The number of items in @c briefGymsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger briefGymsArray_Count;

///需不需要分页?
@property(nonatomic, readwrite) int32_t maxCountPerPage;

@end

#pragma mark - Request13002

typedef GPB_ENUM(Request13002_FieldNumber) {
  Request13002_FieldNumber_Common = 1,
  Request13002_FieldNumber_Params = 2,
};

/// 获取健身房详情
/// /gym/getGymDetail
@interface Request13002 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Request13002_Params *params;
/// Test to see if @c params has been set.
@property(nonatomic, readwrite) BOOL hasParams;

@end

#pragma mark - Request13002_Params

typedef GPB_ENUM(Request13002_Params_FieldNumber) {
  Request13002_Params_FieldNumber_GymId = 1,
};

@interface Request13002_Params : GPBMessage

@property(nonatomic, readwrite) int32_t gymId;

@end

#pragma mark - Response13002

typedef GPB_ENUM(Response13002_FieldNumber) {
  Response13002_FieldNumber_Common = 1,
  Response13002_FieldNumber_Data_p = 2,
};

@interface Response13002 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Response13002_Data *data_p;
/// Test to see if @c data_p has been set.
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - Response13002_Data

typedef GPB_ENUM(Response13002_Data_FieldNumber) {
  Response13002_Data_FieldNumber_DetailGym = 1,
  Response13002_Data_FieldNumber_BriefUsersArray = 2,
  Response13002_Data_FieldNumber_GymCoverArray = 3,
};

@interface Response13002_Data : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) DetailGym *detailGym;
/// Test to see if @c detailGym has been set.
@property(nonatomic, readwrite) BOOL hasDetailGym;

/// 健身房附近的人列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BriefUser*> *briefUsersArray;
/// The number of items in @c briefUsersArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger briefUsersArray_Count;

/// 场馆图片
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *gymCoverArray;
/// The number of items in @c gymCoverArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger gymCoverArray_Count;

@end

#pragma mark - Request13003

typedef GPB_ENUM(Request13003_FieldNumber) {
  Request13003_FieldNumber_Common = 1,
  Request13003_FieldNumber_Params = 2,
};

/// 获取（首页推荐）健身房详情
/// /gym/getRecommendGym
@interface Request13003 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Request13003_Params *params;
/// Test to see if @c params has been set.
@property(nonatomic, readwrite) BOOL hasParams;

@end

#pragma mark - Request13003_Params

typedef GPB_ENUM(Request13003_Params_FieldNumber) {
  Request13003_Params_FieldNumber_Longitude = 1,
  Request13003_Params_FieldNumber_Latitude = 2,
};

@interface Request13003_Params : GPBMessage

@property(nonatomic, readwrite) float longitude;

@property(nonatomic, readwrite) float latitude;

@end

#pragma mark - Response13003

typedef GPB_ENUM(Response13003_FieldNumber) {
  Response13003_FieldNumber_Common = 1,
  Response13003_FieldNumber_Data_p = 2,
};

@interface Response13003 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Response13003_Data *data_p;
/// Test to see if @c data_p has been set.
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - Response13003_Data

typedef GPB_ENUM(Response13003_Data_FieldNumber) {
  Response13003_Data_FieldNumber_DetailGym = 1,
  Response13003_Data_FieldNumber_UserNum = 2,
  Response13003_Data_FieldNumber_TrendNum = 3,
};

@interface Response13003_Data : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) DetailGym *detailGym;
/// Test to see if @c detailGym has been set.
@property(nonatomic, readwrite) BOOL hasDetailGym;

///repeated BriefUser briefUsers = 2;                        // 附近的人列表———》改成数量怎样
///repeated trend trends = 3;//这个直传数量就好
@property(nonatomic, readwrite) int32_t userNum;

@property(nonatomic, readwrite) int32_t trendNum;

@end

#pragma mark - Request13004

typedef GPB_ENUM(Request13004_FieldNumber) {
  Request13004_FieldNumber_Common = 1,
  Request13004_FieldNumber_Params = 2,
};

/// 获取健身房内trend
/// /gym/getRecommendGym
@interface Request13004 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Request13004_Params *params;
/// Test to see if @c params has been set.
@property(nonatomic, readwrite) BOOL hasParams;

@end

#pragma mark - Request13004_Params

typedef GPB_ENUM(Request13004_Params_FieldNumber) {
  Request13004_Params_FieldNumber_GymId = 1,
  Request13004_Params_FieldNumber_PageIndex = 2,
};

@interface Request13004_Params : GPBMessage

@property(nonatomic, readwrite) int32_t gymId;

@property(nonatomic, readwrite) int32_t pageIndex;

@end

#pragma mark - Response13004

typedef GPB_ENUM(Response13004_FieldNumber) {
  Response13004_FieldNumber_Common = 1,
  Response13004_FieldNumber_Data_p = 2,
};

@interface Response13004 : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;
/// Test to see if @c common has been set.
@property(nonatomic, readwrite) BOOL hasCommon;

@property(nonatomic, readwrite, strong, null_resettable) Response13004_Data *data_p;
/// Test to see if @c data_p has been set.
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - Response13004_Data

typedef GPB_ENUM(Response13004_Data_FieldNumber) {
  Response13004_Data_FieldNumber_TrendsArray = 1,
  Response13004_Data_FieldNumber_MaxCountPerPage = 2,
};

@interface Response13004_Data : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Trend*> *trendsArray;
/// The number of items in @c trendsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger trendsArray_Count;

@property(nonatomic, readwrite) int32_t maxCountPerPage;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
