// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reader.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "Reader.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - ReaderRoot

@implementation ReaderRoot

@end


// @@protoc_insertion_point(global_scope)
