// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Request11001_Params;
@class Request11002_Params;
@class RequestCommon;
@class Response11001_Data;
@class Response11002_Data;
@class ResponseCommon;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TokenRoot

@interface TokenRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request11001

typedef GPB_ENUM(Request11001_FieldNumber) {
  Request11001_FieldNumber_Common = 1,
  Request11001_FieldNumber_Params = 2,
};

// 获取七牛token
// /token/getQiniuToken
@interface Request11001 : GPBMessage

// 不需要检查userkey，因为用户未注册是也需要token上传头像
@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11001_Params *params;

@end

#pragma mark - Request11001_Params

@interface Request11001_Params : GPBMessage

@end

#pragma mark - Response11001

typedef GPB_ENUM(Response11001_FieldNumber) {
  Response11001_FieldNumber_Common = 1,
  Response11001_FieldNumber_Data_p = 2,
};

@interface Response11001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11001_Data *data_p;

@end

#pragma mark - Response11001_Data

typedef GPB_ENUM(Response11001_Data_FieldNumber) {
  Response11001_Data_FieldNumber_QiniuToken = 1,
  Response11001_Data_FieldNumber_BucketName = 2,
};

@interface Response11001_Data : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *qiniuToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bucketName;

@end

#pragma mark - Request11002

typedef GPB_ENUM(Request11002_FieldNumber) {
  Request11002_FieldNumber_Common = 1,
  Request11002_FieldNumber_Params = 2,
};

// 获取融云token
// /token/getRongyunToken
@interface Request11002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request11002_Params *params;

@end

#pragma mark - Request11002_Params

typedef GPB_ENUM(Request11002_Params_FieldNumber) {
  Request11002_Params_FieldNumber_OldTokenCannotUse = 1,
};

@interface Request11002_Params : GPBMessage

//旧的token不能使用（服务器需要重新从七牛申请token，而不是拿数据库的token）
@property(nonatomic, readwrite) BOOL oldTokenCannotUse;

@end

#pragma mark - Response11002

typedef GPB_ENUM(Response11002_FieldNumber) {
  Response11002_FieldNumber_Common = 1,
  Response11002_FieldNumber_Data_p = 2,
};

@interface Response11002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response11002_Data *data_p;

@end

#pragma mark - Response11002_Data

typedef GPB_ENUM(Response11002_Data_FieldNumber) {
  Response11002_Data_FieldNumber_RongyunToken = 1,
};

@interface Response11002_Data : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *rongyunToken;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
