// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trend.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Request12001_Params;
@class Request12002_Params;
@class Request12003_Params;
@class Request12004_Params;
@class Request12005_Params;
@class Request12006_Params;
@class Request12007_Params;
@class Request12008_Params;
@class RequestCommon;
@class Response12001_Data;
@class Response12002_Data;
@class Response12003_Data;
@class Response12004_Data;
@class Response12005_Data;
@class Response12006_Data;
@class Response12007_Data;
@class Response12008_Data;
@class ResponseCommon;
@class Trend;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TrendRoot

@interface TrendRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request12001

typedef GPB_ENUM(Request12001_FieldNumber) {
  Request12001_FieldNumber_Common = 1,
  Request12001_FieldNumber_Params = 2,
};

// 发布trend
// /trend/createTrend
@interface Request12001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12001_Params *params;

@end

#pragma mark - Request12001_Params

typedef GPB_ENUM(Request12001_Params_FieldNumber) {
  Request12001_Params_FieldNumber_Content = 1,
  Request12001_Params_FieldNumber_ImageKeysArray = 2,
  Request12001_Params_FieldNumber_BucketName = 3,
  Request12001_Params_FieldNumber_GymId = 4,
};

@interface Request12001_Params : GPBMessage

// 文本内容
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

// 图片的七牛key
// |imageKeysArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *imageKeysArray;
@property(nonatomic, readonly) NSUInteger imageKeysArray_Count;

// 图片上传的bucket
@property(nonatomic, readwrite, copy, null_resettable) NSString *bucketName;

// 所选择的场馆的id
@property(nonatomic, readwrite) int32_t gymId;

@end

#pragma mark - Response12001

typedef GPB_ENUM(Response12001_FieldNumber) {
  Response12001_FieldNumber_Common = 1,
  Response12001_FieldNumber_Data_p = 2,
};

@interface Response12001 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12001_Data *data_p;

@end

#pragma mark - Response12001_Data

@interface Response12001_Data : GPBMessage

@end

#pragma mark - Request12002

typedef GPB_ENUM(Request12002_FieldNumber) {
  Request12002_FieldNumber_Common = 1,
  Request12002_FieldNumber_Params = 2,
};

// 获取我关注的人的trend
// /trend/getMyFollowTrends
@interface Request12002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12002_Params *params;

@end

#pragma mark - Request12002_Params

typedef GPB_ENUM(Request12002_Params_FieldNumber) {
  Request12002_Params_FieldNumber_PageIndex = 1,
};

@interface Request12002_Params : GPBMessage

@property(nonatomic, readwrite) int32_t pageIndex;

@end

#pragma mark - Response12002

typedef GPB_ENUM(Response12002_FieldNumber) {
  Response12002_FieldNumber_Common = 1,
  Response12002_FieldNumber_Data_p = 2,
};

@interface Response12002 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12002_Data *data_p;

@end

#pragma mark - Response12002_Data

typedef GPB_ENUM(Response12002_Data_FieldNumber) {
  Response12002_Data_FieldNumber_TrendsArray = 1,
  Response12002_Data_FieldNumber_MaxCountPerPage = 2,
};

@interface Response12002_Data : GPBMessage

// |trendsArray| contains |Trend|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *trendsArray;
@property(nonatomic, readonly) NSUInteger trendsArray_Count;

// 用于分页。判断能否加载更多
@property(nonatomic, readwrite) int32_t maxCountPerPage;

@end

#pragma mark - Request12003

typedef GPB_ENUM(Request12003_FieldNumber) {
  Request12003_FieldNumber_Common = 1,
  Request12003_FieldNumber_Params = 2,
};

// 通过id获取trend详情
// /trend/getTrendById
@interface Request12003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12003_Params *params;

@end

#pragma mark - Request12003_Params

typedef GPB_ENUM(Request12003_Params_FieldNumber) {
  Request12003_Params_FieldNumber_TrendId = 1,
};

@interface Request12003_Params : GPBMessage

@property(nonatomic, readwrite) int32_t trendId;

@end

#pragma mark - Response12003

typedef GPB_ENUM(Response12003_FieldNumber) {
  Response12003_FieldNumber_Common = 1,
  Response12003_FieldNumber_Data_p = 2,
};

@interface Response12003 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12003_Data *data_p;

@end

#pragma mark - Response12003_Data

typedef GPB_ENUM(Response12003_Data_FieldNumber) {
  Response12003_Data_FieldNumber_Trend = 1,
};

@interface Response12003_Data : GPBMessage

@property(nonatomic, readwrite) BOOL hasTrend;
@property(nonatomic, readwrite, strong, null_resettable) Trend *trend;

@end

#pragma mark - Request12004

typedef GPB_ENUM(Request12004_FieldNumber) {
  Request12004_FieldNumber_Common = 1,
  Request12004_FieldNumber_Params = 2,
};

// 获取trend的评论列表
// /trend/getTrendComment
@interface Request12004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12004_Params *params;

@end

#pragma mark - Request12004_Params

typedef GPB_ENUM(Request12004_Params_FieldNumber) {
  Request12004_Params_FieldNumber_TrendId = 1,
  Request12004_Params_FieldNumber_PageIndex = 2,
};

@interface Request12004_Params : GPBMessage

@property(nonatomic, readwrite) int32_t trendId;

@property(nonatomic, readwrite) int32_t pageIndex;

@end

#pragma mark - Response12004

typedef GPB_ENUM(Response12004_FieldNumber) {
  Response12004_FieldNumber_Common = 1,
  Response12004_FieldNumber_Data_p = 2,
};

@interface Response12004 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12004_Data *data_p;

@end

#pragma mark - Response12004_Data

typedef GPB_ENUM(Response12004_Data_FieldNumber) {
  Response12004_Data_FieldNumber_CommentsArray = 1,
  Response12004_Data_FieldNumber_MaxCountPerPage = 2,
};

@interface Response12004_Data : GPBMessage

// |commentsArray| contains |Comment|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *commentsArray;
@property(nonatomic, readonly) NSUInteger commentsArray_Count;

// 用于分页
@property(nonatomic, readwrite) int32_t maxCountPerPage;

@end

#pragma mark - Request12005

typedef GPB_ENUM(Request12005_FieldNumber) {
  Request12005_FieldNumber_Common = 1,
  Request12005_FieldNumber_Params = 2,
};

// 给trend点赞或者取消点赞
// /trend/likeTrend
@interface Request12005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12005_Params *params;

@end

#pragma mark - Request12005_Params

typedef GPB_ENUM(Request12005_Params_FieldNumber) {
  Request12005_Params_FieldNumber_TrendId = 1,
  Request12005_Params_FieldNumber_LikeTrend = 2,
};

@interface Request12005_Params : GPBMessage

@property(nonatomic, readwrite) int32_t trendId;

// true:点赞 false：取消点赞
@property(nonatomic, readwrite) BOOL likeTrend;

@end

#pragma mark - Response12005

typedef GPB_ENUM(Response12005_FieldNumber) {
  Response12005_FieldNumber_Common = 1,
  Response12005_FieldNumber_Data_p = 2,
};

@interface Response12005 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12005_Data *data_p;

@end

#pragma mark - Response12005_Data

@interface Response12005_Data : GPBMessage

@end

#pragma mark - Request12006

typedef GPB_ENUM(Request12006_FieldNumber) {
  Request12006_FieldNumber_Common = 1,
  Request12006_FieldNumber_Params = 2,
};

// 评论trend
// /trend/commentTrend
@interface Request12006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12006_Params *params;

@end

#pragma mark - Request12006_Params

typedef GPB_ENUM(Request12006_Params_FieldNumber) {
  Request12006_Params_FieldNumber_TrendId = 1,
  Request12006_Params_FieldNumber_ToCommentId = 2,
  Request12006_Params_FieldNumber_ToUserId = 3,
  Request12006_Params_FieldNumber_Content = 4,
  Request12006_Params_FieldNumber_GymId = 5,
};

@interface Request12006_Params : GPBMessage

@property(nonatomic, readwrite) int32_t trendId;

// 如果回复别人的评论，需要加上这个
@property(nonatomic, readwrite) int32_t toCommentId;

// 如果回复别人的评论，需要加上这个
@property(nonatomic, readwrite) int32_t toUserId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite) int32_t gymId;

@end

#pragma mark - Response12006

typedef GPB_ENUM(Response12006_FieldNumber) {
  Response12006_FieldNumber_Common = 1,
  Response12006_FieldNumber_Data_p = 2,
};

@interface Response12006 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12006_Data *data_p;

@end

#pragma mark - Response12006_Data

@interface Response12006_Data : GPBMessage

@end

#pragma mark - Request12007

typedef GPB_ENUM(Request12007_FieldNumber) {
  Request12007_FieldNumber_Common = 1,
  Request12007_FieldNumber_Params = 2,
};

// 删除自己的评论
// /trend/deleteComment
@interface Request12007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12007_Params *params;

@end

#pragma mark - Request12007_Params

typedef GPB_ENUM(Request12007_Params_FieldNumber) {
  Request12007_Params_FieldNumber_TrendId = 1,
  Request12007_Params_FieldNumber_CommentId = 2,
};

@interface Request12007_Params : GPBMessage

@property(nonatomic, readwrite) int32_t trendId;

@property(nonatomic, readwrite) int32_t commentId;

@end

#pragma mark - Response12007

typedef GPB_ENUM(Response12007_FieldNumber) {
  Response12007_FieldNumber_Common = 1,
  Response12007_FieldNumber_Data_p = 2,
};

@interface Response12007 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12007_Data *data_p;

@end

#pragma mark - Response12007_Data

@interface Response12007_Data : GPBMessage

@end

#pragma mark - Request12008

typedef GPB_ENUM(Request12008_FieldNumber) {
  Request12008_FieldNumber_Common = 1,
  Request12008_FieldNumber_Params = 2,
};

// 删除我的trend
// /trend/deleteTrend
@interface Request12008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) RequestCommon *common;

@property(nonatomic, readwrite) BOOL hasParams;
@property(nonatomic, readwrite, strong, null_resettable) Request12008_Params *params;

@end

#pragma mark - Request12008_Params

typedef GPB_ENUM(Request12008_Params_FieldNumber) {
  Request12008_Params_FieldNumber_TrendId = 1,
};

@interface Request12008_Params : GPBMessage

@property(nonatomic, readwrite) int32_t trendId;

@end

#pragma mark - Response12008

typedef GPB_ENUM(Response12008_FieldNumber) {
  Response12008_FieldNumber_Common = 1,
  Response12008_FieldNumber_Data_p = 2,
};

@interface Response12008 : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) ResponseCommon *common;

@property(nonatomic, readwrite) BOOL hasData_p;
@property(nonatomic, readwrite, strong, null_resettable) Response12008_Data *data_p;

@end

#pragma mark - Response12008_Data

@interface Response12008_Data : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
