// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.xiang.proto.pilot.nano;

@SuppressWarnings("hiding")
public interface Pilot {

  public static final class Request10001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string phone = 1;
      public java.lang.String phone;

      // optional string username = 2;
      public java.lang.String username;

      // optional string avatarKey = 3;
      public java.lang.String avatarKey;

      // optional string bucketName = 4;
      public java.lang.String bucketName;

      // optional string password = 5;
      public java.lang.String password;

      // optional .com.xiang.proto.Sex sex = 6;
      public int sex;

      public Params() {
        clear();
      }

      public Params clear() {
        phone = "";
        username = "";
        avatarKey = "";
        bucketName = "";
        password = "";
        sex = com.xiang.proto.nano.Common.MALE;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.phone.equals("")) {
          output.writeString(1, this.phone);
        }
        if (!this.username.equals("")) {
          output.writeString(2, this.username);
        }
        if (!this.avatarKey.equals("")) {
          output.writeString(3, this.avatarKey);
        }
        if (!this.bucketName.equals("")) {
          output.writeString(4, this.bucketName);
        }
        if (!this.password.equals("")) {
          output.writeString(5, this.password);
        }
        if (this.sex != com.xiang.proto.nano.Common.MALE) {
          output.writeInt32(6, this.sex);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.phone.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.phone);
        }
        if (!this.username.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.username);
        }
        if (!this.avatarKey.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(3, this.avatarKey);
        }
        if (!this.bucketName.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(4, this.bucketName);
        }
        if (!this.password.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(5, this.password);
        }
        if (this.sex != com.xiang.proto.nano.Common.MALE) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.sex);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.phone = input.readString();
              break;
            }
            case 18: {
              this.username = input.readString();
              break;
            }
            case 26: {
              this.avatarKey = input.readString();
              break;
            }
            case 34: {
              this.bucketName = input.readString();
              break;
            }
            case 42: {
              this.password = input.readString();
              break;
            }
            case 48: {
              int value = input.readInt32();
              switch (value) {
                case com.xiang.proto.nano.Common.MALE:
                case com.xiang.proto.nano.Common.FEMALE:
                  this.sex = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request10001[] _emptyArray;
    public static Request10001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request10001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request10001.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request10001.Params params;

    public Request10001() {
      clear();
    }

    public Request10001 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request10001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request10001.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request10001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request10001(), data);
    }

    public static Request10001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request10001().mergeFrom(input);
    }
  }

  public static final class Response10001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional int32 userId = 1;
      public int userId;

      // optional string userKey = 2;
      public java.lang.String userKey;

      public Data() {
        clear();
      }

      public Data clear() {
        userId = 0;
        userKey = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.userId != 0) {
          output.writeInt32(1, this.userId);
        }
        if (!this.userKey.equals("")) {
          output.writeString(2, this.userKey);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.userId != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, this.userId);
        }
        if (!this.userKey.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.userKey);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.userId = input.readInt32();
              break;
            }
            case 18: {
              this.userKey = input.readString();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response10001[] _emptyArray;
    public static Response10001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response10001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response10001.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response10001.Data data;

    public Response10001() {
      clear();
    }

    public Response10001 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response10001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response10001.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response10001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response10001(), data);
    }

    public static Response10001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response10001().mergeFrom(input);
    }
  }

  public static final class Request10002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string phone = 1;
      public java.lang.String phone;

      // optional string password = 2;
      public java.lang.String password;

      public Params() {
        clear();
      }

      public Params clear() {
        phone = "";
        password = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.phone.equals("")) {
          output.writeString(1, this.phone);
        }
        if (!this.password.equals("")) {
          output.writeString(2, this.password);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.phone.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.phone);
        }
        if (!this.password.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.password);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.phone = input.readString();
              break;
            }
            case 18: {
              this.password = input.readString();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request10002[] _emptyArray;
    public static Request10002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request10002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request10002.Params params = 2;
    public com.xiang.proto.pilot.nano.Pilot.Request10002.Params params;

    public Request10002() {
      clear();
    }

    public Request10002 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request10002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Pilot.Request10002.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request10002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request10002(), data);
    }

    public static Request10002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request10002().mergeFrom(input);
    }
  }

  public static final class Response10002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .com.xiang.proto.BriefUser briefUser = 1;
      public com.xiang.proto.nano.Common.BriefUser briefUser;

      // optional string userKey = 2;
      public java.lang.String userKey;

      // optional string rongyunToken = 3;
      public java.lang.String rongyunToken;

      public Data() {
        clear();
      }

      public Data clear() {
        briefUser = null;
        userKey = "";
        rongyunToken = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.briefUser != null) {
          output.writeMessage(1, this.briefUser);
        }
        if (!this.userKey.equals("")) {
          output.writeString(2, this.userKey);
        }
        if (!this.rongyunToken.equals("")) {
          output.writeString(3, this.rongyunToken);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.briefUser != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.briefUser);
        }
        if (!this.userKey.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.userKey);
        }
        if (!this.rongyunToken.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(3, this.rongyunToken);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.briefUser == null) {
                this.briefUser = new com.xiang.proto.nano.Common.BriefUser();
              }
              input.readMessage(this.briefUser);
              break;
            }
            case 18: {
              this.userKey = input.readString();
              break;
            }
            case 26: {
              this.rongyunToken = input.readString();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response10002[] _emptyArray;
    public static Response10002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response10002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response10002.Data data = 2;
    public com.xiang.proto.pilot.nano.Pilot.Response10002.Data data;

    public Response10002() {
      clear();
    }

    public Response10002 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response10002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Pilot.Response10002.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response10002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response10002(), data);
    }

    public static Response10002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response10002().mergeFrom(input);
    }
  }
}
