// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.xiang.proto.pilot.nano;

@SuppressWarnings("hiding")
public interface Token {

  public static final class Request11001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      public Params() {
        clear();
      }

      public Params clear() {
        cachedSize = -1;
        return this;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11001[] _emptyArray;
    public static Request11001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11001.Params params = 2;
    public com.xiang.proto.pilot.nano.Token.Request11001.Params params;

    public Request11001() {
      clear();
    }

    public Request11001 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Token.Request11001.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11001(), data);
    }

    public static Request11001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11001().mergeFrom(input);
    }
  }

  public static final class Response11001 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string qiniuToken = 1;
      public java.lang.String qiniuToken;

      public Data() {
        clear();
      }

      public Data clear() {
        qiniuToken = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.qiniuToken.equals("")) {
          output.writeString(1, this.qiniuToken);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.qiniuToken.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.qiniuToken);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.qiniuToken = input.readString();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11001[] _emptyArray;
    public static Response11001[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11001[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11001.Data data = 2;
    public com.xiang.proto.pilot.nano.Token.Response11001.Data data;

    public Response11001() {
      clear();
    }

    public Response11001 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11001 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Token.Response11001.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11001 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11001(), data);
    }

    public static Response11001 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11001().mergeFrom(input);
    }
  }

  public static final class Request11002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Params extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Params[] _emptyArray;
      public static Params[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Params[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bool oldTokenCannotUse = 1;
      public boolean oldTokenCannotUse;

      public Params() {
        clear();
      }

      public Params clear() {
        oldTokenCannotUse = false;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.oldTokenCannotUse != false) {
          output.writeBool(1, this.oldTokenCannotUse);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.oldTokenCannotUse != false) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeBoolSize(1, this.oldTokenCannotUse);
        }
        return size;
      }

      @Override
      public Params mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.oldTokenCannotUse = input.readBool();
              break;
            }
          }
        }
      }

      public static Params parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Params(), data);
      }

      public static Params parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Params().mergeFrom(input);
      }
    }

    private static volatile Request11002[] _emptyArray;
    public static Request11002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Request11002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.RequestCommon common = 1;
    public com.xiang.proto.nano.Common.RequestCommon common;

    // optional .com.xiang.proto.pilot.Request11002.Params params = 2;
    public com.xiang.proto.pilot.nano.Token.Request11002.Params params;

    public Request11002() {
      clear();
    }

    public Request11002 clear() {
      common = null;
      params = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.params != null) {
        output.writeMessage(2, this.params);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.params != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.params);
      }
      return size;
    }

    @Override
    public Request11002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.RequestCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.params == null) {
              this.params = new com.xiang.proto.pilot.nano.Token.Request11002.Params();
            }
            input.readMessage(this.params);
            break;
          }
        }
      }
    }

    public static Request11002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Request11002(), data);
    }

    public static Request11002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Request11002().mergeFrom(input);
    }
  }

  public static final class Response11002 extends
      com.google.protobuf.nano.MessageNano {

    public static final class Data extends
        com.google.protobuf.nano.MessageNano {

      private static volatile Data[] _emptyArray;
      public static Data[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Data[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string rongyunToken = 1;
      public java.lang.String rongyunToken;

      public Data() {
        clear();
      }

      public Data clear() {
        rongyunToken = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.rongyunToken.equals("")) {
          output.writeString(1, this.rongyunToken);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.rongyunToken.equals("")) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.rongyunToken);
        }
        return size;
      }

      @Override
      public Data mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.rongyunToken = input.readString();
              break;
            }
          }
        }
      }

      public static Data parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Data(), data);
      }

      public static Data parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Data().mergeFrom(input);
      }
    }

    private static volatile Response11002[] _emptyArray;
    public static Response11002[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Response11002[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .com.xiang.proto.ResponseCommon common = 1;
    public com.xiang.proto.nano.Common.ResponseCommon common;

    // optional .com.xiang.proto.pilot.Response11002.Data data = 2;
    public com.xiang.proto.pilot.nano.Token.Response11002.Data data;

    public Response11002() {
      clear();
    }

    public Response11002 clear() {
      common = null;
      data = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.common != null) {
        output.writeMessage(1, this.common);
      }
      if (this.data != null) {
        output.writeMessage(2, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.common != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.common);
      }
      if (this.data != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.data);
      }
      return size;
    }

    @Override
    public Response11002 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.common == null) {
              this.common = new com.xiang.proto.nano.Common.ResponseCommon();
            }
            input.readMessage(this.common);
            break;
          }
          case 18: {
            if (this.data == null) {
              this.data = new com.xiang.proto.pilot.nano.Token.Response11002.Data();
            }
            input.readMessage(this.data);
            break;
          }
        }
      }
    }

    public static Response11002 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Response11002(), data);
    }

    public static Response11002 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Response11002().mergeFrom(input);
    }
  }
}
